### PR TITLE
Top nodes only

### PR DESCRIPTION
**Pull request by sammyj85**
- Added a --top-nodes-only flag, which cuts out duplication of nodes such that they only appear once. If a node has a parent, it is only displayed under that parent.
- Added a --show-class flag, which displays the class name in a second column, which is useful for seeing the diagnostics that have no associated class (and are thus dummy diagnostics which have no effect).
- Added warning output files alongside the existing ones.
- Added change details to the README. Added warning output for Clang 3.7 to the README.

### CODE REVIEW

**Comment by Barro** [comment]
Hmm, these additions look somewhat interesting by providing some extra information, but I'm not really sure the extra verbosity is a good idea. Originally I made these lists to be such that they can be copy-pasted around and easily filtered with something like grep and at the same time provide information that what other flags a specific warning flag enables. Now this looks to be diverging too much from this original intent and adds a lot of extra stuff that is not necessarily needed for the main task.

**Comment by sammyj85** [comment]
Okay, I don't have a strong idea of what extra processing you would do with the output of this tool.
So it looks like you have a problem with the --show-class flag, which is fair enough (it's off by default). The only use I actually have for it is seeing if a diagnostic has <<<NONE>>> for the class, in which case I can tell it is a useless diagnostic that does nothing. That is quite valuable to me, and quite possibly other people. Perhaps that flag could be renamed and refined such that it prints nothing for the second column, except for those that have NONE for the class. Other variants could include 1) not printing those that have NONE class (if they have no children), 2) making a distinction between those that have NONE and have children vs those that have NONE class and don't have children. Some nodes that have children have a class (which means it has an effect in itself), and other nodes that have children have NONE as the class, which means it is just a grouping with no effect in itself.
So to be honest, I don't have a use for the actual class name except for NONE. Do any of the above suggestions sound appealing to you?

Do you have any comments about the --top-nodes-only flag? If you have a better name for it, suggest away. Feel free to do a diff between the output with and without this flag to get an idea. This does not add any extra output, but in fact removes lines from the output (original is 817 lines vs 488 lines with --top-nodes-only with Clang 3.7, for example). Your comment didn't seem to say anything about this, so do you have any comments on this flag? To me, this flag is the most useful. I am not interested in seeing -Wformat-y2k (for example) appear under -Wall, -Wmost -Wformat, itself - -Wformat-y2k, and then -Wformat=2. With --top-nodes-only, this then only displays it under the topmost node, -Wall, and then an alternative diagnostic -Wformat=2. Without --top-nodes-only, the output has very limited use to me.

**Comment by sammyj85** [comment]
The main use case I have for --top-nodes-only is to answer the question "what diagnostics are not turned on by -Wall / -Wextra?".
This is very useful to me, and presumably other people, such as these (GCC-oriented question):
http://stackoverflow.com/questions/399850/best-compiler-warning-level-for-c-c-compilers

**Comment by Barro** [comment]
Yeah, now that I had time to look at it more closely those both options look quite nice. My original idea was to also display those options that can get displayed multiple times as normal command line options, but by default it would be probably nice to hide options that are also enabled by other ones. Especially the fact that there are dummy warning options in clang is quite useful information to people (probably going to add "# dummy switch" or something like that after the command line option). I can also create multiple lists that have different properties, like listing everything, filtering out switches that get enabled by some other switch, and differences between different compiler versions.

I'll take those in after doing some refactoring. Especially command line arguments should be parsed by Python's argparse module and I generally try to avoid using backslash in my code to divide output to multiple lines (see section about long lines in PEP8 https://www.python.org/dev/peps/pep-0008/#id17). It might take a while as my free time hacking chances are currently quite limited. But no worries, these both are good ideas that I definitely want to incorporate into these lists.

**Comment by sammyj85** [comment]
Ah, good to hear your plans, and that we're on the same page now. :)

I am by no means a Python expert, and most of usage is from mimicking examples and searching stackoverflow. Yep, improved argument parsing is good. Conforming to standard multi-line practices is good too. I don't quite get what you were suggesting to use instead of slashes to continue on the next line - the link says to limit to 79 (or a bit more if people agree). Yours was beyond that, so I wasn't sure of your line width. It says implicit line continuations by using brackets is preferred to slashes... but what do you do if that isn't what the line contains? So that confused me. I'm not as used to strict whitespace, because I normally use C/C++.

**Comment by sammyj85** [comment]
Also, unrelated to the pull request - you've included links to GCC 5.1, 5.2, 5.3, but they are all minor revisions of version 5, and thus no features (no diagnostics) were added. So it would be equivalent to listing GCC 4.9.0, 4.9.1, 4.9.2. I suggest just listing GCC 5 (and you can use whatever latest minor revision is available for generating it).

**Comment by Barro** [comment]
Yeah, seems so that GCC 5 changed how version numbers indicate changes.

**Comment by Barro** [comment]
I have now included lists and changes to display filtered results. No list of dummy options yet, though.

**Comment by sammyj85** [comment]
Hey, I had a quick glance - looks good!
Yeah, GCC moved to "Firefox versioning". If it were me, I would just call it GCC 5 instead of GCC 5.x (because we don't mention 4.9.x).
I'm liking the top level / unique / diff listings - they're great. It now needs to be implemented for GCC too. And the "dummy options" thing too would be good, if you can.
The Usage section should be updated to include the --unique and --top-level command line options.
And GCC 6 will arrive any day, so that can be added too. :)
I could even commit a new branch with some of the changes when I get time too.

**Comment by Barro** [comment]
Switches that supposedly do nothing are now highlighted with a specific dummy switch marker. I'll close this pull request as things that were discussed here seem to be implemented now.

**Pull request closed without merging**
